### ISSUE TITLE
Error: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by sacsbrainz** [hatoo/oha#247] opened 2023-06-26 20:30 UTC
when i try to run a benchmark i get error say:
``
Error: No such file or directory (os error 2)
``
![Screenshot from 2023-06-26 21-21-18](https://github.com/hatoo/oha/assets/40229306/674034b7-000f-469b-896b-6a0535989e69)

<br/>
what i ran:
```sh
oha -z 10s -c 500 --latency-correction --disable-keepalive http://127.0.0.1:3000
```

i tried installing it via the 2 methods of rust, i still got same error when i ran a benchmark
i also tried installing via debian installation method, when i run the benchmark it gives same error

my specs
os: ubuntu 22.04.1
![Screenshot from 2023-06-26 21-23-16](https://github.com/hatoo/oha/assets/40229306/e1ab5c29-3c6f-4276-b7f4-2a1fb9d623e5)

**Comment by hatoo** [comment] 2023-06-27 07:50
Thanks for reporting!

I couldn't reproduce it but I'm guessing [trust-dns](https://github.com/bluejekyll/trust-dns) failed to load the system configuration.

1. Could you check `oha` is working with `-h`?

```
oha -h
```

2. Please copypate the output of 
```
strace oha -n 1 --no-tui http://127.0.0.1:3000  2>&1  | grep open
```

**Comment by sacsbrainz** [comment] 2023-06-27 07:55
yes oha is working ```oha -h```

![Screenshot from 2023-06-27 08-54-18](https://github.com/hatoo/oha/assets/40229306/b149299c-b297-4050-95fa-26562d9c7bed)

**Comment by sacsbrainz** [comment] 2023-06-27 07:56
strace
```sh
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
open("/proc/sys/vm/overcommit_memory", O_RDONLY|O_CLOEXEC) = 3
open("/sys/kernel/mm/transparent_hugepage/enabled", O_RDONLY) = 3
openat(AT_FDCWD, "/proc/self/maps", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/proc/self/cgroup", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/proc/self/mountinfo", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/app.slice/app-org.gnome.Terminal.slice/vte-spawn-1b45dfde-520c-44f1-a0d1-8cf40d6f63e6.scope/cpu.max", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/resolv.conf", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

```

**Comment by sacsbrainz** [comment] 2023-06-27 08:18
i have fixed the issues turns out my /etc/resolv.conf was corrpt so i had to delete it and make a new one from the /etc/resolv.conf.default

**Comment by hatoo** [comment] 2023-06-27 08:25
Great.
I close this issue but feel free to reopen it if you want.

**Closed by hatoo** 2023-06-27 08:25 UTC
